version: '2'
services:
  apparmor:
    build:
      context: ./apparmor
      dockerfile: Dockerfile
    privileged: true
    restart: 'no'
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
    environment:
      - 'ENFORCE=1'
  test:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - apparmor
    environment:
      - 'ENFORCE=1'
